//! Criterion Benchmark for ScriptGo HFT Lock-Free RCU Strategy Hot-Reloading & Market Tick Processing
#[macro_use] extern crate covopt_macro;
use covopt_macro::covopt_param;

use arc_swap::ArcSwap;
use criterion::{black_box, criterion_group, criterion_main, Criterion, Throughput};
use script_go::assembler::parse_asm;
use script_go::instruction::Instruction;
use script_go::vm::{ScriptVm, VmResult};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

/// High-Frequency Trading Market Tick update representing level-1 order book data.
#[derive(Debug, Clone, Copy)]
pub struct MarketTick {
    pub sequence_number: u64,
    pub timestamp_nanoseconds: u64,
    pub bid_price: u32,
    pub ask_price: u32,
    pub bid_quantity: u32,
    pub ask_quantity: u32,
}

/// Trading decision signal generated by evaluating an SGL strategy script.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TradingSignal {
    Hold,
    Buy { price: u32, quantity: u32 },
    Sell { price: u32, quantity: u32 },
}

/// An immutable Trading Strategy container holding compiled SGL bytecode and metadata.
#[derive(Debug, Clone)]
pub struct TradingStrategy {
    pub strategy_identifier: u32,
    pub strategy_version: u32,
    pub strategy_name: String,
    pub target_spread_threshold: u32,
    pub compiled_bytecode: Vec<Instruction>,
}

impl TradingStrategy {
    pub fn new(
        strategy_identifier: u32,
        strategy_version: u32,
        strategy_name: impl Into<String>,
        target_spread_threshold: u32,
        assembly_source: &str,
    ) -> Self {
        let compiled_bytecode = parse_asm(assembly_source)
            .expect("Failed to assemble trading strategy SGL script code");
        Self {
            strategy_identifier,
            strategy_version,
            strategy_name: strategy_name.into(),
            target_spread_threshold,
            compiled_bytecode,
        }
    }
}

/// Lock-Free HFT Strategy Engine using RCU (`ArcSwap`) for zero-downtime, sub-microsecond strategy hot-reloading.
pub struct LockFreeStrategyEngine {
    pub active_strategy: ArcSwap<TradingStrategy>,
}

impl LockFreeStrategyEngine {
    pub fn new(initial_strategy: TradingStrategy) -> Self {
        Self {
            active_strategy: ArcSwap::new(Arc::new(initial_strategy)),
        }
    }

    /// Evaluates incoming market tick against current active strategy without acquiring any lock on reader path.
    #[inline(always)]
    pub fn evaluate_market_tick(
        &self,
        market_tick: &MarketTick,
        script_vm_instance: &mut ScriptVm,
    ) -> TradingSignal {
        let current_strategy = self.active_strategy.load();

        script_vm_instance.registers[0] = 0;
        script_vm_instance.registers[1] = market_tick.bid_price;
        script_vm_instance.registers[2] = market_tick.ask_price;
        script_vm_instance.registers[covopt_param!("M_87_37", 3)] = current_strategy.target_spread_threshold;
        script_vm_instance.registers[covopt_param!("M_88_37", 4)] = market_tick.bid_quantity;
        script_vm_instance.registers[covopt_param!("M_89_37", 5)] = market_tick.ask_quantity;

        script_vm_instance.pc = 0;

        match script_vm_instance.run(&current_strategy.compiled_bytecode) {
            Ok(VmResult::Halted(_steps)) => match script_vm_instance.registers[0] {
                1 => TradingSignal::Buy {
                    price: market_tick.ask_price,
                    quantity: covopt_param!("M_97_30", 10),
                },
                2 => TradingSignal::Sell {
                    price: market_tick.bid_price,
                    quantity: covopt_param!("M_101_30", 10),
                },
                _ => TradingSignal::Hold,
            },
            _ => TradingSignal::Hold,
        }
    }

    /// Atomically updates active strategy using RCU mechanism.
    pub fn hot_reload_strategy(&self, new_strategy: TradingStrategy) {
        self.active_strategy.store(Arc::new(new_strategy));
    }
}

fn generate_benchmark_strategies() -> (TradingStrategy, TradingStrategy) {
    let assembly_v1 = r#"
        SUB 6 2 1
        JMPIFGT 6 3 4
        LOADIMM 0 0 0
        HALT
        LOADIMM 0 1 0
        HALT
    "#;

    let assembly_v2 = r#"
        JMPIFGT 4 5 3
        LOADIMM 0 2 0
        HALT
        LOADIMM 0 1 0
        HALT
    "#;

    let strategy_v1 = TradingStrategy::new(covopt_param!("M_133_43", 101), 1, "Conservative Spread Strategy", covopt_param!("M_133_83", 5), assembly_v1);
    let strategy_v2 = TradingStrategy::new(covopt_param!("M_134_43", 102), 2, "Aggressive Imbalance Strategy", covopt_param!("M_134_84", 3), assembly_v2);

    (strategy_v1, strategy_v2)
}

fn generate_benchmark_market_ticks(number_of_ticks: usize) -> Vec<MarketTick> {
    let mut ticks = Vec::with_capacity(number_of_ticks);
    for index in 0..number_of_ticks {
        let sequence_number = (index + 1) as u64;
        ticks.push(MarketTick {
            sequence_number,
            timestamp_nanoseconds: sequence_number * covopt_param!("M_145_53", 100),
            bid_price: covopt_param!("M_146_23", 100) + ((index % covopt_param!("M_146_39", 5)) as u32),
            ask_price: covopt_param!("M_147_23", 105) + ((index % covopt_param!("M_147_39", 5)) as u32),
            bid_quantity: covopt_param!("M_148_26", 50) + ((index % covopt_param!("M_148_41", 20)) as u32),
            ask_quantity: covopt_param!("M_149_26", 40) + ((index % covopt_param!("M_149_41", 30)) as u32),
        });
    }
    ticks
}

fn bench_rcu_strategy_hot_swap_latency(c: &mut Criterion) {
    let mut group = c.benchmark_group("hft_rcu_hot_swap_latency");
    let (strategy_v1, strategy_v2) = generate_benchmark_strategies();
    let engine = LockFreeStrategyEngine::new(strategy_v1.clone());

    group.bench_function("uncontended_rcu_hot_swap", |b| {
        let mut toggle_state = false;
        b.iter(|| {
            let next_strategy = if toggle_state {
                strategy_v1.clone()
            } else {
                strategy_v2.clone()
            };
            toggle_state = !toggle_state;
            engine.hot_reload_strategy(black_box(next_strategy));
        });
    });

    group.finish();
}

fn bench_market_tick_execution_throughput(c: &mut Criterion) {
    let mut group = c.benchmark_group("hft_market_tick_execution_throughput");
    let number_of_ticks = covopt_param!("M_178_26", 10000);
    let market_ticks = generate_benchmark_market_ticks(number_of_ticks);
    let (strategy_v1, _) = generate_benchmark_strategies();
    let engine = LockFreeStrategyEngine::new(strategy_v1);

    group.throughput(Throughput::Elements(number_of_ticks as u64));

    group.bench_function("single_thread_tick_evaluation", |b| {
        let mut script_vm_instance = ScriptVm::new();
        b.iter(|| {
            let mut signal_accumulator = 0u32;
            for market_tick in market_ticks.iter() {
                let signal = engine.evaluate_market_tick(black_box(market_tick), &mut script_vm_instance);
                match signal {
                    TradingSignal::Buy { .. } => signal_accumulator += 1,
                    TradingSignal::Sell { .. } => signal_accumulator += 2,
                    TradingSignal::Hold => signal_accumulator += 0,
                }
            }
            black_box(signal_accumulator);
        });
    });

    group.finish();
}

fn bench_contended_hft_hot_reload_throughput(c: &mut Criterion) {
    let mut group = c.benchmark_group("hft_contended_hot_reload_throughput");
    let number_of_ticks = covopt_param!("M_206_26", 5000);
    let market_ticks = generate_benchmark_market_ticks(number_of_ticks);
    let (strategy_v1, strategy_v2) = generate_benchmark_strategies();

    let engine = Arc::new(LockFreeStrategyEngine::new(strategy_v1.clone()));
    let execution_running_flag = Arc::new(AtomicBool::new(true));

    // Spawn background hot-reloader thread
    let writer_engine = engine.clone();
    let writer_running_flag = execution_running_flag.clone();
    let writer_strategy_v1 = strategy_v1.clone();
    let writer_strategy_v2 = strategy_v2.clone();

    let writer_thread_handle = thread::Builder::new()
        .name("bench-hot-reloader".to_string())
        .spawn(move || {
            no_std_tool::debug::track_thread_spawn();
            let mut toggle = false;
            while writer_running_flag.load(Ordering::Relaxed) {
                let next_strategy = if toggle {
                    writer_strategy_v1.clone()
                } else {
                    writer_strategy_v2.clone()
                };
                toggle = !toggle;
                writer_engine.hot_reload_strategy(next_strategy);
                thread::sleep(Duration::from_micros(covopt_param!("M_232_52", 10)));
            }
            no_std_tool::debug::track_thread_exit();
        })
        .expect("Failed to spawn bench hot-reloader thread");

    // Spawn 2 background reader threads
    let number_of_background_readers = 2usize;
    let mut reader_thread_handles = Vec::with_capacity(number_of_background_readers);

    for reader_index in 0..number_of_background_readers {
        let reader_engine = engine.clone();
        let reader_running_flag = execution_running_flag.clone();

        let reader_handle = thread::Builder::new()
            .name(format!("bench-bg-reader-{}", reader_index))
            .spawn(move || {
                no_std_tool::debug::track_thread_spawn();
                let mut script_vm_instance = ScriptVm::new();
                let local_ticks = generate_benchmark_market_ticks(covopt_param!("M_251_66", 100));
                while reader_running_flag.load(Ordering::Relaxed) {
                    for tick in local_ticks.iter() {
                        let signal = reader_engine.evaluate_market_tick(tick, &mut script_vm_instance);
                        black_box(signal);
                    }
                    thread::sleep(Duration::from_micros(covopt_param!("M_257_56", 5)));
                }
                no_std_tool::debug::track_thread_exit();
            })
            .expect("Failed to spawn bench background reader thread");

        reader_thread_handles.push(reader_handle);
    }

    group.throughput(Throughput::Elements(number_of_ticks as u64));

    group.bench_function("contended_reader_tick_evaluation", |b| {
        let mut script_vm_instance = ScriptVm::new();
        b.iter(|| {
            let mut signal_accumulator = 0u32;
            for market_tick in market_ticks.iter() {
                let signal = engine.evaluate_market_tick(black_box(market_tick), &mut script_vm_instance);
                match signal {
                    TradingSignal::Buy { .. } => signal_accumulator += 1,
                    TradingSignal::Sell { .. } => signal_accumulator += 2,
                    TradingSignal::Hold => signal_accumulator += 0,
                }
            }
            black_box(signal_accumulator);
        });
    });

    // Clean up background threads
    execution_running_flag.store(false, Ordering::Relaxed);
    writer_thread_handle.join().expect("Writer thread panicked");
    for handle in reader_thread_handles {
        handle.join().expect("Reader thread panicked");
    }

    assert!(
        no_std_tool::debug::check_thread_drops(),
        "All benchmark threads should be cleanly dropped."
    );

    group.finish();
}

criterion_group!(
    benches,
    bench_rcu_strategy_hot_swap_latency,
    bench_market_tick_execution_throughput,
    bench_contended_hft_hot_reload_throughput
);
criterion_main!(benches);
